# Generated by Django 4.2.6 on 2023-10-27 09:02

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمات کلیدی')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت')),
                ('stock', models.IntegerField(default=1, verbose_name='موجودی در انبار')),
                ('image', models.ImageField(upload_to=extensions.utils.upload_product_image_path, verbose_name='تصویر محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'جزئیات محصول',
                'ordering': ('-created',),
            },
        ),
    ]
